version: '3.8'

services:
  luisenriquemata-web:
    build: .
    container_name: luisenriquemata-landing
    ports:
      - "8000:8000"
      - "80:8000"    # También mapear al puerto 80
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Servicio de monitoreo (opcional)
  watchtower:
    image: containrrr/watchtower
    container_name: luisenriquemata-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup luisenriquemata-landing
    restart: unless-stopped
